### PR TITLE
Referral support

### PR DESCRIPTION
**Pull request by uzrbin**
Not sure you'll want to pull this.  It uses Optional so breaks Java 7 compatibility and I didn't write any test cases.  But hopefully it'll be useful in some regard?

### CODE REVIEW

**Comment by maxgrabenhorst** [comment]
Hi, thanks for this PR that adds missing functionality. To get this PR merged please ensure java 7 compatibility and add integration test cases. Let me know if you could to this. Would be really appreciated.

**Comment by uzrbin** [comment]
Hey, my free time is a bit tight these days.  I did this work for a client, I'll see if they have any interest in me getting this pulled. Though java.util.Date is so painful I half want to fork this lovely library to a Java 8 version.

**Comment by maxgrabenhorst** [comment]
Hey, ok I understand. A Java 8 version is planned leveraging the new date time api, optionals, etc.
I suggest to leave this PR open. I will use your code with attribution to you.

Ok?

**Comment by uzrbin** [comment]
Absolutely, please feel free to use any of this. Sorry I don't have time to contribute more.

Cheers

**Pull request closed without merging**
