### PR TITLE
Add support for email and phone number quick replies

### PR DESCRIPTION
**Pull request by jjtindale**
Hey @maxgrabenhorst, this PR adds support for sending email and phone number quick replies. I added a corresponding issue (https://github.com/messenger4j/messenger4j/issues/76). 

It was a very small amount of work so I decided to go ahead and implement it straight away without discussing it, but feel free to add your feedback and let me know if I should change anything.

### CODE REVIEW

**Comment by xcapdevila** [comment]
Hi @jjtindale nice work!

It's working properly ;)

**Comment by maxgrabenhorst** [comment]
Hi @jjtindale,
thanks for your PR! Love that you contribute actively!
Unfortunately I'm not able to release a new version prior the second week in April. Therefore I will have a look at the PR later. Hope this is okay for you.

**Comment by jjtindale** [comment]
Hi @maxgrabenhorst, absolutely fine. I enjoy helping out where I can.

**Comment by maxgrabenhorst** [comment]
Thanks @jjtindale for your work!!

**Pull request merged**
