### PR TITLE
Add support for text and attachment echo messages

### PR DESCRIPTION
**Pull request by alberthoekman**

### CODE REVIEW

**Comment by maxgrabenhorst** [comment]
Hi Albert, thanks for your PR. I think this is a useful enhancement. A few comments on this:
* a lot of my code is now annotated with your name instead of mine ;) (especially the moved files)
* can you please remove all things related to gradle? I think maven as build tool is fine at the moment, or what was your intention?
* I changed the target branch of this PR to v0.9.0. So it is not required to change the pom.xml
* I think my simple EchoMessageEvent is not required anymore. Or what is your reason for not removing it?
Thanks, Max

**Comment by alberthoekman** [comment]
Hello Mark,

Thank you for considering my pull-request. To answer your questions:

- I get what you mean with the moved files, but do you also want me to annotate the new files with your name?
- I’m sorry this got into the pull-request. We use gradle for our own build at the moment. I will remove it.
- Alright
- I left it in there for backwards compatibility. Should I annotate it with @deprecated or something?

I will make a new commit soon, since I’m quite busy at the moment.

M.V.G. Albert Hoekman


On 20 March 2017 at 23:55:38, Max Grabenhorst (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi Albert, thanks for your PR. I think this is a useful enhancement. A few comments on this:

  *   a lot of my code is now annotated with your name instead of mine ;) (especially the moved files)
  *   can you please remove all things related to gradle? I think maven as build tool is fine at the moment, or what was your intention?
  *   I changed the target branch of this PR to v0.9.0. So it is not required to change the pom.xml
  *   I think my simple EchoMessageEvent is not required anymore. Or what is your reason for not removing it?
Thanks, Max

**Comment by maxgrabenhorst** [comment]
Hi Albert,

since I've written the moved files I thinks it's appropriate that they are annotated with my name ;) To be clear: yes.
Generally it's (of course) a great idea to provide backward compatibility but since messenger4j has not reached version 1.0 and the messenger platform at all is changing fast, we should remove the old EchoMessageEvent. It's a breaking change but the effort to fix this should be small on user side.
Please squash and rebase your commits when you are done.

No hurry, take your time - and thanks!
Max

**Comment by alberthoekman** [comment]
Alright, thanks for the clarification. I will see when I have the time.

M.V.G. Albert Hoekman


On 24 March 2017 at 08:50:07, Max Grabenhorst (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi Albert,

since I've written the moved files I thinks it's appropriate that they are annotated with my name ;) To be clear: yes.
Generally it's (of course) a great idea to provide backward compatibility but since messenger4j has not reached version 1.0 and the messenger platform at all is changing fast, we should remove the old EchoMessageEvent. It's a breaking change but the effort to fix this should be small on user side.
Please squash and rebase your commits when you are done.

No hurry, take your time - and thanks!
Max

**Pull request closed without merging**
